matrix:
  include:
  - os: linux
    dist: bionic
    addons:
      apt:
        packages:
        - g++-7
        - libgmp-dev
        - libmpfr-dev
        - libmpc-dev
        - iverilog
    env:
    - CC=gcc-7
    - CXX=g++-7
  - os: osx
    osx_image: xcode10.2
    addons:
      homebrew:
        packages:
          - icarus-verilog

install:
# Get conda installer
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi

# Install conda (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html)
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a

# create and activate conda environment
- conda create -q -n test-env python=3.7.3
- conda activate test-env

# install pip so that we can install other packages
- conda install pip

# speed up the build process until it's fixed at z3
# see https://github.com/Z3Prover/z3/issues/2800
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    pip install https://github.com/Z3Prover/z3/releases/download/Nightly/z3_solver-4.8.8.0-py2.py3-none-macosx_10_14_x86_64.whl
  fi

# install various python dependencies
- pip install pytest mantle fault pytest-cov

# install svreal
- pip install -e .

script:
- pytest --cov-report=xml --cov=svreal tests/ -v -r s
- bash <(curl -s https://codecov.io/bash)
