steps:
  - command: |
      source /etc/environment
      echo $$PATH
      python3.7 -m venv venv
      source venv/bin/activate
      pip install pytest
      pip install -e .
      pytest tests
      deactivate
    label: "test_emu"
    timeout_in_minutes: 60
    agents:
        fpga_verif: "true"
