name: Regression

on:
  push:
  pull_request:
  schedule:
  - cron: 0 11 * * ?

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: sudo apt-get install g++-7 libgmp-dev libmpfr-dev libmpc-dev iverilog
    - name: Run regression test
      env:
        CC: gcc-7
        CXX: g++-7
      run: source regress.sh
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  mac:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: brew install icarus-verilog
    - name: Run regression test
      run: source regress.sh
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
